### PR TITLE
Update to v6.0.0 (NOTE BELOW)

### PR DESCRIPTION
**Pull request by TheComputerGuy96**
PLEASE tell Brinker why you LOVE ~/.local/share/grapejuice/logs so much :pleading_face: :pleading_face: :pleading_face:

Real change description: Also remove semi-obsolete hack (and adjust Studio prefix setting to fix crashes)

### CODE REVIEW

**Comment by TacticalTux** [comment]
Why nu ~/.local/share/grapejuice/logs???? 🥺 🥺 🥺 🥺 🥺 🥺

**Review by lunarlattice0 — COMMENTED** [review]
Looks good, will run final test.

**Comment by lunarlattice0** [comment]
bot, build net.brinkervii.grapejuice

**Comment by lunarlattice0** [comment]
I'm going to put off merging this for a while, since Brinker has identified issues with the new version.

**Comment by lunarlattice0** [comment]
We're on version 6.2.1 now I guess

**Comment by lunarlattice0** [comment]
Confirmed working, merging now.

**Pull request merged**
