### PR TITLE
Drop all custom patches

### PR DESCRIPTION
**Pull request by guihkx**
Most of the changes included in these patches can be configured with environment variables instead.

To achieve this, however, it was necessary to include the `glxinfo` tool provided by [mesa-demos](https://gitlab.freedesktop.org/mesa/demos), which is used by Grapejuice to profile the hardware and configure the rendering backend automatically.

With these changes, there's no need to maintain a custom `user_settings.json` anymore, because Grapejuice can now decide the recommended rendering backend Roblox should use, based on the GPU installed:

```
$ flatpak run net.brinkervii.grapejuice gui
[INFO] grapejuice/root:- Log level was set to 'INFO'
[INFO] grapejuice/root:- The log file is stored at '~/.var/app/net.brinkervii.grapejuice/data/grapejuice/logs/2023-03-31_03-22-40_grapejuice.log'
[INFO] grapejuice/common_prepare:- Using locale directory /app/share/locale
[INFO] grapejuice/grapejuice_common.features.settings:- There is no settings file present, going to save one
[INFO] grapejuice/grapejuice_common.features.settings:- Going to profile hardware
[INFO] grapejuice/grapejuice_common.hardware_info.hardware_profile:- Computing hardware profile parameters
[INFO] grapejuice/grapejuice_common.hardware_info.hardware_profile:- Getting lspci and XRandR data
[INFO] grapejuice/grapejuice_common.hardware_info.xrandr_factory:- Creating XRandR instance
[INFO] grapejuice/grapejuice_common.hardware_info.hardware_profile:- Got multiple graphics cards: False
[INFO] grapejuice/grapejuice_common.hardware_info.hardware_profile:- There is only one graphics card installed, pick the 0th one
[INFO] grapejuice/grapejuice_common.hardware_info.graphics_card:- Could not find ICD at '/usr/share/vulkan/icd.d/nvidia_icd.json'
[INFO] grapejuice/grapejuice_common.hardware_info.graphics_card:- Could not find ICD at '~/.var/app/net.brinkervii.grapejuice/data/vulkan/icd.d/nvidia_icd.json'
[INFO] grapejuice/grapejuice_common.hardware_info.hardware_profile:- Card is a wacky nVidia one, use mesa gl override
[INFO] grapejuice/grapejuice_common.hardware_info.hardware_profile:- Prefer OpenGL renderer
```

---

The changes above were the "major" ones. But I've also included some other minor changes:

- **Add .gitignore**:
  Exclude some files and directories created by `flatpak-builder`. This is only useful when building locally.

- **Remove `--socket=wayland` permission:**
  At the moment, Wayland is not really usable with the Wine version we ship. Additionally, this silences following warning given by [flatpak-builder-lint](https://github.com/flathub/flatpak-builder-lint):

  ```
  {
      "warnings": [
          "finish-args-contains-both-x11-and-wayland"
      ]
  }
  ```

- **Move patched Wine into a separate module:**
  Makes local builds much faster to complete, thanks to `flatpak-builder`'s module caching mechanism.

- **Improve Grapejuice install steps**:
  - Extract the package created by Grapejuice's packaging module directly into `/app`, which makes us not having to manually copy Python modules, icons and whatnot.
  - Any step that tweaks already-installed files, have been moved to the `post-install` section.

### CODE REVIEW

**Comment by guihkx** [comment]
Actually, this is isn't quite right.

`patch_binaries.patch` was also creating this `user_settings_brinkerwine.json` file, and I haven't addressed that.

I'll convert this PR into a draft for now, and I'll work on removing all non-upstream patches/files.

**Comment by guihkx** [comment]
I've renamed the pull request and changed its description to better describe the new changes I added, so you may want to read it again. :P

I also recommend renaming/removing `~/.var/app/net.brinkervii.grapejuice` to properly test these changes on a clean environment.

**Comment by TheComputerGuy96** [comment]
I should probably make a change to Grapejuice which will remove both `xrandr` and `glxinfo` dependencies (with a SDL2/PyOpenGL-based profiler)

Also I should make a Wine build that has Alexandros' Wayland driver (and some other stuff) so we can replace `--socket=x11` with `--socket=fallback-x11` and `wayland` (`fallback-x11` will still be likely needed for both DWM chads and NVIDIA users and of course regular people which don't care what their Linux system uses) 🐸

**Comment by lunarlattice0** [comment]
Nice work @guihkx, I'll merge this PR for now and will await for @TheComputerGuy96's changes.

**Pull request merged**
